app = "synapse-ai-backend"
primary_region = "iad"

[build]

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[deploy]
  release_command = "python -m app.database"

# Environment variables to be set in Fly.io dashboard:
# OPENAI_API_KEY=your_openai_api_key_here
# ANTHROPIC_API_KEY=your_anthropic_api_key_here
# DATABASE_URL=your_postgresql_database_url_here
# JWT_SECRET_KEY=your_jwt_secret_key_here
# STRIPE_SECRET_KEY=your_stripe_secret_key_here
# STRIPE_PUBLISHABLE_KEY=your_stripe_publishable_key_here
# STRIPE_WEBHOOK_SECRET=your_stripe_webhook_secret_here
# SENDGRID_API_KEY=your_sendgrid_api_key_here
# CORS_ORIGIN_URL=https://your-frontend-domain.vercel.app
